[build]
target = "kernel/x86_64-femdos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
bindeps = true

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
